@startuml
actor Client
participant "quotes.views.get_similar_quotes_of_selected_quote" as get_similar_quotes_of_selected_quote
participant "quotes.views.get_related_quote_by_quote_id" as get_related_quote_by_quote_id
participant "DRF Response" as Response

Client -> get_similar_quotes_of_selected_quote: POST /getsimilarquotesofselectedquote
get_similar_quotes_of_selected_quote -> get_related_quote_by_quote_id: get_related_quote_by_quote_id(quote_id, include_effective_date)
get_similar_quotes_of_selected_quote -> Response: Response(res)
@enduml